Comment out console.log("Not a medium blog :( ");
issammani/unlimited-medium pull request #22
Opened 2023-04-25 00:34 UTC by tog22

As discussed in our email thread, here's submitting a PR

2023-04-25 16:17 UTC, issammani requested changes
Thanks for opening a PR ! I have a few minor comments 😄

2023-04-25 16:17 UTC, issammani commented on app/src/js/content.js
> +        console.log("Unlimited Medium extension: medium blog detected");
Let's remove the log all together. This is used mainly for debugging. In the future, I might add a proper logging mechanism and this line would be replaced by a call to `logger.debug` which would print only in dev mode and not in production.

2023-04-25 16:17 UTC, issammani commented on app/src/js/content.js
> +        // console.log("Not a medium blog :( "); // disabled to prevent console pollution
Same here. Let's remove it instead of commenting it out.

2023-04-26 14:50 UTC, tog22 commented
Sure thing, I just submitted another commit to my repo, which is now showing up in this pull request. Is that the right way to do these things?

2023-04-26 15:25 UTC, issammani approved these changes
Looks good ! Thanks @tog22

2023-04-26 15:26 UTC, issammani commented
> Sure thing, I just submitted another commit to my repo, which is now showing up in this pull request. Is that the right way to do these things?

Yes ! That's exactly how you do it 😄 Thanks for the contribution 👍

2023-04-26 15:27 UTC, merged

2023-04-26 17:16 UTC, tog22 commented
Thanks for the guidance 🙂 This was my first contribution to a project like this.

Thanks also for the extension. Have a great rest of your week.